### PR TITLE
Added null check for endpointSubset.getAddresses()

### LINKED ISSUE #43: NPE when no ready pods reported in Endpoints
#### Note
Potentially duplicate of #29

## Scenario
When an HZ instance boots up and the ServiceEndpointResolver kicks in with a provided serviceName the retrieved Endpoints object via fabric8 Kubernetes-Client is iterated over endpoints.getSubsets() and endpointSubset.getAddresses(). But the latter is null because there are no ready endpoints. Raw json response:

````
{
  "kind": "Endpoints",
  "apiVersion": "v1",
  "metadata": {
    "name": "demo-service-9aadd30",
    "namespace": "dev",
    "selfLink": "/api/v1/namespaces/dev/endpoints/demo-service-9aadd30",
    "uid": "8a4fcf99-92ea-11e7-846d-005056b85198",
    "resourceVersion": "10935908",
    "creationTimestamp": "2017-09-06T10:02:49Z",
    "labels": {
      "appName": "demo-service",
      "chart": "demo-service-1.0.7-SNAPSHOT",
      "release": "demo-service-9aadd30"
    }
  },
  "subsets": [
    {
      "notReadyAddresses": [
        {
          "ip": "172.16.1.60",
          "nodeName": "node03",
          "targetRef": {
            "kind": "Pod",
            "namespace": "dev",
            "name": "demo-service-9aadd30-3817585861-dd1zz",
            "uid": "4abc9584-92f5-11e7-846d-005056b85198",
            "resourceVersion": "10935516"
          }
        },
        {
          "ip": "172.16.1.61",
          "nodeName": "comp03",
          "targetRef": {
            "kind": "Pod",
            "namespace": "dev",
            "name": "demo-service-9aadd30-test",
            "uid": "c4f0c539-9302-11e7-bbe2-005056b89983",
            "resourceVersion": "10935907"
          }
        },
        {
          "ip": "172.16.3.56",
          "nodeName": "comp05",
          "targetRef": {
            "kind": "Pod",
            "namespace": "dev",
            "name": "demo-service-9aadd30-3817585861-w56dd",
            "uid": "4ab4c940-92f5-11e7-846d-005056b85198",
            "resourceVersion": "10935514"
          }
        },
        {
          "ip": "172.16.8.53",
          "nodeName": "comp06",
          "targetRef": {
            "kind": "Pod",
            "namespace": "dev",
            "name": "demo-service-9aadd30-2520348926-b9d5p",
            "uid": "d0ef3797-92f4-11e7-846d-005056b85198",
            "resourceVersion": "10935702"
          }
        }
      ],
      "ports": [
        {
          "name": "service-port",
          "port": 8080,
          "protocol": "TCP"
        },
        {
          "name": "hazelcast-port",
          "port": 5701,
          "protocol": "TCP"
        }
      ]
    }
  ]
}
````

The same request but with a fake bootstrap-pod with matching selectors yields:
````

{
  "kind": "Endpoints",
  "apiVersion": "v1",
  "metadata": {
    "name": "demo-service-9aadd30",
    "namespace": "dev",
    "selfLink": "/api/v1/namespaces/dev/endpoints/demo-service-9aadd30",
    "uid": "8a4fcf99-92ea-11e7-846d-005056b85198",
    "resourceVersion": "10936092",
    "creationTimestamp": "2017-09-06T10:02:49Z",
    "labels": {
      "appName": "demo-service",
      "chart": "demo-service-1.0.7-SNAPSHOT",
      "release": "demo-service-9aadd30"
    }
  },
  "subsets": [
    {
      "addresses": [
        {
          "ip": "172.16.1.61",
          "nodeName": "comp03",
          "targetRef": {
            "kind": "Pod",
            "namespace": "dev",
            "name": "demo-service-9aadd30-test",
            "uid": "c4f0c539-9302-11e7-bbe2-005056b89983",
            "resourceVersion": "10936091"
          }
        }
      ],
      "notReadyAddresses": [
        {
          "ip": "172.16.1.60",
          "nodeName": "comp03",
          "targetRef": {
            "kind": "Pod",
            "namespace": "dev",
            "name": "demo-service-9aadd30-3817585861-dd1zz",
            "uid": "4abc9584-92f5-11e7-846d-005056b85198",
            "resourceVersion": "10935516"
          }
        },
        {
          "ip": "172.16.3.56",
          "nodeName": "comp05",
          "targetRef": {
            "kind": "Pod",
            "namespace": "dev",
            "name": "demo-service-9aadd30-3817585861-w56dd",
            "uid": "4ab4c940-92f5-11e7-846d-005056b85198",
            "resourceVersion": "10935514"
          }
        },
        {
          "ip": "172.16.8.53",
          "nodeName": "comp06",
          "targetRef": {
            "kind": "Pod",
            "namespace": "dev",
            "name": "demo-service-9aadd30-2520348926-b9d5p",
            "uid": "d0ef3797-92f4-11e7-846d-005056b85198",
            "resourceVersion": "10935702"
          }
        }
      ],
      "ports": [
        {
          "name": "service-port",
          "port": 8080,
          "protocol": "TCP"
        },
        {
          "name": "hazelcast-port",
          "port": 5701,
          "protocol": "TCP"
        }
      ]
    }
  ]
}
````
And the deployment is successfull.

## Culprint
Internal fabric8 uses Jackson to unmarshel json to Endpoints an non-existing addresses JSON-objects results to a null value for the addresses field. Hence https://github.com/hazelcast/hazelcast-kubernetes/blob/4884098044c729da87769478281318a4e2652ae3/src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java#L116 produces a NullPointerException.

## Possible solution
Add a null check on each subsets loop. e.g. :
````
if (endpointSubset.getAddresses() == null) {
       continue;
 }
````

### PR DESCRIPTION
**Pull request by mrahbar**
Resolves #43

### CODE REVIEW

**Comment by googlielmo** [comment]
verify

**Comment by mrahbar** [comment]
@googlielmo I added a testcase but might messed up the history. I rebased with master due to a conflict but this introduced even more conflicts. Any idea how to resolve them?

**Comment by googlielmo** [comment]
Hi @mrahbar looking into it now

**Comment by googlielmo** [comment]
@mrahbar As it stands, it's probably easier if you just open a new PR against master, with the null check and the new test :-)

**Pull request closed without merging**
