### PR TITLE
Rebase 4.0 compatibility

### PR DESCRIPTION
**Pull request by hasancelik**

### CODE REVIEW

**Comment by hasancelik** [comment]
> Are we going to set 1.5.2 as latest dependency on hazelcast-all-3.12.4?

It makes sense, we can update hazelcast version atmaintenance branch.

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
@mesutcelik here is the related PR --> https://github.com/hazelcast/hazelcast/pull/15693

**Comment by hasancelik** [comment]
@leszko I thought like you at the first place but we are doing all development on master branch. After beta release period, we would need to maintain `4.0-compatibility` branch as well.

**Comment by leszko** [comment]
> @leszko I thought like you at the first place but we are doing all development on master branch. After beta release period, we would need to maintain `4.0-compatibility` branch as well.

ok 👍

**Pull request merged**
