### PR TITLE
Hazelcast Version updated to 3.9.3 and other version updates

### PR DESCRIPTION
**Pull request by mmuruganandam**
Hazelcast Version updated to 3.9.3, kubernetes client to 3.1.10, dnsjava to 2.1.8 and powermock to 1.7.3

### CODE REVIEW

**Comment by mesutcelik** [comment]
verify

**Comment by mesutcelik** [comment]
Hi @mmuruganandam ,
Can you please sign our CLA?
https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement

Have you tried Hazelcast official docker image which is supporting 3.9.3?
https://github.com/hazelcast/hazelcast-docker/tree/v3.9.3/hazelcast-kubernetes
https://store.docker.com/community/images/hazelcast/hazelcast-kubernetes/tags

**Comment by mmuruganandam** [comment]
@mesutcelik Just signed and sent the CLA.

**Comment by mmuruganandam** [comment]
This is what we use for hazelcast deployed in kubernetes.
"https://github.com/hazelcast/hazelcast-docker/tree/v3.9.3/hazelcast-kubernetes"

The hazelcast client in my experience always needed to be same version of the hazelcast node or, I have/had issues in the past.

**Comment by mesutcelik** [comment]
Thanks for the info. Normally you shouldn't have an problem because of the client protocol introduced in hazelcast 3.6

You can see the compatibility matrix here.
https://hazelcast.org/clients-languages/compatibility-matrix/

**Comment by mesutcelik** [comment]
Thanks @mmuruganandam for the contribution!

**Pull request merged**
