### PR TITLE
OAuth Token Does Not Get Logged

### PR DESCRIPTION
**Pull request by JanMosigItemis**
Hi there,

I recently noticed a glitch in com.hazelcast.kubernetes.ServiceEndpointResolver.buildKubernetesClient(String, String): If the provided apiToken is empty, the code does load the token from file correctly but logs the "old" apiToken, which results in a misleading log entry.

### CODE REVIEW

**Comment by emrahkocaman** [comment]
Hi @JanMosigItemis , this is a good catch thanks. 
I'd prefer getting rid of [this](https://github.com/hazelcast/hazelcast-kubernetes/blob/master/src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java#L68) unnecessary assignment instead by just using the incoming `apiToken` parameter and assign it the returned value from `getAuthToken` if it's null. (Also we can change the name `apiToken` to `token`). 
WDY? Would you like to jump in and make this change?

**Comment by JanMosigItemis** [comment]
Thanks for the comment. In general it is a smell to reassign method arguments, but I think the general intention of the assignment was already lost so this seems to be ok here. I will try to implement the changes if it is still possible / necessary (the branch has become a bit old since February).

**Comment by JanMosigItemis** [comment]
@emrahkocaman I updated the PR. Could you please have another look?

**Comment by emrahkocaman** [comment]
@JanMosigItemis Great, thanks! I just noticed that you're not in the contributors list.  Could you please sign "Contributer Agreement Form" and send it to us? Details can be found [here](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)

**Comment by JanMosigItemis** [comment]
@emrahkocaman will do. May take some time.

**Comment by JanMosigItemis** [comment]
@emrahkocaman I signed, scanned and sent the form to Jaromir.

**Comment by emrahkocaman** [comment]
Thanks @JanMosigItemis, your contributions are much appreciated.

**Pull request merged**
