### PR TITLE
Add configurable support for add endpoints of pods not still ready on kubernetes

### PR DESCRIPTION
**Pull request by amiranda-ob**
Configurable version of feature commented on https://github.com/hazelcast/hazelcast-kubernetes/pull/37

### CODE REVIEW

**Comment by googlielmo** [comment]
verify

**Comment by googlielmo** [comment]
Fixes #56

**Comment by mesutcelik** [comment]
Hi @amiranda-ob ,
Thanks a lot for the contribution!

Can you please sign [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement) and send back to us?

**Comment by deradam** [comment]
Wow, this is exactly what we need. @amiranda-ob please go ahead and sign the agreement :) And thanks for the great work!

**Comment by deradam** [comment]
Great, happy to see it is merged. We have already tested the new feature and it does exactly what we need. When can we expect this be available as a non-snapshot version on maven central?

**Comment by hasancelik** [comment]
Hi @deradam,
We will probably release new version in the next week.

Thanks again for the contribution 👍

**Comment by hasancelik** [comment]
Hi @deradam ,

New version([1.1.0](https://github.com/hazelcast/hazelcast-kubernetes/releases/tag/v1.1.0)) is available at [maven central](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22hazelcast-kubernetes%22).

**Pull request merged**
