### PR TITLE
Failed to connect to kubernetes

### PR DESCRIPTION
**Pull request by sebasmoyano**
Related to issue https://github.com/hazelcast/hazelcast-kubernetes/issues/28.

Added retrying in case Kubernetes API server throws an error. 
- Max attemps: 10.
- Retry wait up period: current number of retries (in seconds).

### CODE REVIEW

**Comment by emrahkocaman** [comment]
verify

**Comment by emrahkocaman** [comment]
Hi @sebasmoyano thanks for your interest, and it's been sometime since the opening of this PR sorry for that. Let's heat this up and merge if you're still interested. WDY?

**Comment by sebasmoyano** [comment]
Sure. Let me check failing tests.

**Comment by sebasmoyano** [comment]
All tests passed successfully. Could you please re-check?

**Comment by emrahkocaman** [comment]
verify

**Comment by emrahkocaman** [comment]
@sebasmoyano , Looks like `checkstyle` has been failed. Could you please have a look?  `checkstyle` profile can be run locally, i.e. `mvn clean install -Pcheckstyle`

**Comment by sebasmoyano** [comment]
Tests have been fixed.

**Comment by emrahkocaman** [comment]
verify

**Comment by emrahkocaman** [comment]
LGTM. @lazerion Could you please have a look too?

**Comment by emrahkocaman** [comment]
@sebasmoyano Could you please sign our CLA to allow us merging your PR? Details can be found [here](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement).

**Comment by sebasmoyano** [comment]
Done. I have sent the agreement signed to Jaromir.

**Comment by googlielmo** [comment]
Hi @sebasmoyano would you please rebase on master?

**Comment by googlielmo** [comment]
Hi @sebasmoyano we hope you're still interested, as we'd like to move forward and merge this. It would be great if you could rebase on master and address the comments above. Thanks!

**Comment by googlielmo** [comment]
Hi @sebasmoyano please see comment above if you can. We'd like to move forward with this PR.
Thanks!

**Comment by googlielmo** [comment]
Closing this PR for inactivity. Feel free to reopen this or create a new PR for completing this implementation.

**Pull request closed without merging**
