### PR TITLE
Allow multiple Hazelcast instances in the same namespace with different labels

### PR DESCRIPTION
**Pull request by codepfleger**
This change is necessary to support multiple Hazelcast instances in the same namespace with different service labels. Without it the second instance will always pick up the other one (with a different label), due to the fail-over implementation in resolve() (see the unit-test).
Viele Grüße aus Bern :-)

### CODE REVIEW

**Comment by codepfleger** [comment]
FYI: The resolving by service-name also doesn't work due to a bug in Kubernetes. I''ve submitted a PR to fix it.

**Comment by codepfleger** [comment]
Pretty much like: https://github.com/hazelcast/hazelcast-kubernetes/pull/17
But with a test :-p

**Comment by codepfleger** [comment]
Linked to Issue https://github.com/hazelcast/hazelcast-kubernetes/issues/16

**Comment by noctarius** [comment]
Hey Frank,

Thanks for the fix. Can you elaborate the fix a bit? Is the current version just broken? Can you also please sign the CLA (Contributors License Agreement, https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement).

Thanks,
Chris

**Comment by codepfleger** [comment]
Hi Chris, thanks for the quick response.
The current version has unpredictable and wrong behaviour, therefore I think it's a bug. I don't think it makes sense to have a failover logic in the resolve() method. When you're providing a serviceLabel and serviceLabelValue you normally only want exactly those instances to be a part of the cluster.
With the current implementation it is not possible to have 2 HZ clusters in the same namespace identified by a label. 

Imagine you want to startup cluster 1 with label app=A and cluster 2 with label app=B.
Starting up cluster 1 works fine as there is no other HZ node in the namespace.
During startup of cluster 2 there will be no matching node with label app=B but due to the failover logic it will look for all nodes in the namespace (finding cluster 1 with label app=A).
This in turn leads to one big cluster instead  of 2 separate clusters.

I signed and mailed the CLA.

Frank

**Comment by noctarius** [comment]
Hey @JacpFX, I think you did the original implementation, didn't you? Can you have a look?

**Comment by codepfleger** [comment]
As a sidenode:
Looking up by service-name also doesn't work, as io.fabric8.kubernetes.client.dsl.base.BaseOperation.list() calls getNamespacedUrl() instead of getResourceUrl() and therefore ignores the service-name.
I filed a PR but it needs some fixes... https://github.com/fabric8io/kubernetes-client/pull/626

**Comment by emrahkocaman** [comment]
Hi @codepfleger As hazelcast-kubernetes repo is making its way to be an official Hazelcast plugin, there've been some changes in the package names. Could you please rebase your branch and update the PR?

**Comment by codepfleger** [comment]
@emrahkocaman done

**Comment by emrahkocaman** [comment]
Thx @codepfleger , looks like there is a problem with commit history. There are some unrelated changes in the commit history. 
Could you please have a look at this? Maybe there can be better ways but I generally do a soft reset,  stash my changes, rebase and then reapply my changes in a single commit for such cases.

**Comment by emrahkocaman** [comment]
Can you also please sign the CLA (Contributors License Agreement, https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement).?

**Comment by codepfleger** [comment]
@emrahkocaman Seems to be better now... Sorry

**Comment by codepfleger** [comment]
I already signed and mailed the CLA. Not sure why it hasn't been processed yet.

**Comment by emrahkocaman** [comment]
verify

**Comment by emrahkocaman** [comment]
@codepfleger Looks like your email didn't reach to us. Could you please send your CLA to [me](mailto:emrah@hazelcast.com) to get things done faster?

**Comment by codepfleger** [comment]
Did again with a different mail account. Looks like the other one gets blocked.

**Comment by noctarius** [comment]
It looks good from my side but I'm not really familiar with the labels, @JacpFX can you take a quick look?

**Comment by codepfleger** [comment]
It's not just about the labels (the title might be a little misleading). This also fixes the unexpected behaviour when no HZ cluster is running yet with the specified service-name OR label (see comment above).

**Comment by amoAHCP** [comment]
Hi @codepfleger, as I can see, you simply removed the fallback...thats ok for me. But I do not really understand the behavior you described:

"Imagine you want to startup cluster 1 with label app=A and cluster 2 with label app=B.
Starting up cluster 1 works fine as there is no other HZ node in the namespace.
During startup of cluster 2 there will be no matching node with label app=B but due to the failover logic it will look for all nodes in the namespace (finding cluster 1 with label app=A).
This in turn leads to one big cluster instead of 2 separate clusters."

Where did you define your label? Normally I deploy my Services (with the labels) before my pods...

Grüsse aus Zürich ;-)

**Comment by codepfleger** [comment]
Yes, even if the service (with or w/o label) is already deployed it won't work.
The condition for the failover-logic is not "service has been found" but "nodes within service have been found". That's why the first node starting up will always fall back to the failover-logic, potentially joining the wrong HZ cluster.

**Comment by googlielmo** [comment]
LGTM

**Pull request merged**
