### PR TITLE
Use default namespace from filesystem

### PR DESCRIPTION
**Pull request by geertvanheusden**
IMO it makes more sense to check the current namespace than using the "default" one.
This PR changes the behaviour when the namespace is not configured and the env vars are not set, to look at the file system for the namespace rather than defaulting to "default".

### CODE REVIEW

**Comment by leszko** [comment]
@geertvanheusden Thanks a lot for the change. I really like it.

However, IMO we should merge it only to `master` (#184), since the change is non-backwards-compatible. So, I'll review your change in #184 .

Thanks again.

**Comment by geertvanheusden** [comment]
Hi @leszko, you're welcome!

I understand your "non-backwards-compatible" concern although I don't really see a difference with the recent change that was merged were the `resolveNotReadyAddresses` default was changed from `false` to `true`. Didn't this break backwards compatibility as well?

**Comment by leszko** [comment]
Yeah, I agree. I think we should revert the `resolveNotReadyAddresses` change from `3.12.x` and keep the `3.12.x` backwards-compatible with all the changes. 

And all the non-backwards-compatible changes should be done to `master` since they'll be released in `4.0`. @mesutcelik @hasancelik , what do you think?

**Comment by hasancelik** [comment]
> And all the non-backwards-compatible changes should be done to master since they'll be released in 4.0. @mesutcelik @hasancelik , what do you think?

Yes, that is our plan. @leszko @geertvanheusden you are right about `resolveNotReadyAddresses` change, I missed out while syncing branches. I will revert  it from `3.12.x` branch.

btw, Thanks a lot for your contribution @geertvanheusden 👍

**Comment by leszko** [comment]
@hasancelik Thanks for reverting the change. Closing this one.

**Pull request closed without merging**
